import { useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, BarChart3, Bell, Boxes, CalendarDays, Car, ChevronDown, CircleDollarSign, Dumbbell, GraduationCap, HeartPulse, Home, LayoutDashboard, LogIn, MoreHorizontal, PackagePlus, Plus, Receipt, Search, Settings, ShieldCheck, ShoppingCart, Sparkles, Store, Ticket, Users, Utensils, Wallet, X } from 'lucide-react'
import './App.css'

type Expense = { id: number; description: string; category: string; date: string; amount: number; color: string }
type InventoryItem = { id: number; name: string; sku: string; category: string; stock: number; reorderAt: number; value: number; status: 'In stock' | 'Low stock' | 'Out of stock' }
const initialExpenses: Expense[] = [
  { id: 1, description: 'Wholesale coffee beans', category: 'Inventory', date: 'Today, 09:42', amount: 1840, color: 'mint' },
  { id: 2, description: 'Shop rent - September', category: 'Operations', date: 'Sep 16, 2024', amount: 2200, color: 'lavender' },
  { id: 3, description: 'Social media campaign', category: 'Marketing', date: 'Sep 14, 2024', amount: 480, color: 'peach' },
  { id: 4, description: 'Packaging supplies', category: 'Inventory', date: 'Sep 12, 2024', amount: 365, color: 'sky' },
]
const initialInventory: InventoryItem[] = [
  { id: 1, name: 'House Blend Coffee', sku: 'COF-001', category: 'Coffee', stock: 42, reorderAt: 20, value: 1260, status: 'In stock' },
  { id: 2, name: 'Ceramic Mug - White', sku: 'MER-014', category: 'Merchandise', stock: 8, reorderAt: 12, value: 184, status: 'Low stock' },
  { id: 3, name: 'Cold Brew Bottle', sku: 'DRK-022', category: 'Drinks', stock: 0, reorderAt: 10, value: 0, status: 'Out of stock' },
  { id: 4, name: 'Oat Milk 1L', sku: 'SUP-008', category: 'Supplies', stock: 26, reorderAt: 8, value: 130, status: 'In stock' },
]
const navItems = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Expenses', icon: Receipt }, { label: 'Inventory', icon: Boxes }, { label: 'Sales', icon: ShoppingCart }, { label: 'Reports', icon: BarChart3 }]
const expenseCategories = [{ name: 'Fixed expenses', icon: Home, color: 'sage' }, { name: 'Shopping', icon: Store, color: 'apricot' }, { name: 'Food', icon: Utensils, color: 'rose' }, { name: 'Medical', icon: HeartPulse, color: 'pink' }, { name: 'Transportation', icon: Car, color: 'lilac' }, { name: 'Fitness', icon: Dumbbell, color: 'blue' }, { name: 'Entertainment', icon: Ticket, color: 'teal' }, { name: 'Family & education', icon: GraduationCap, color: 'olive' }]
const money = (value: number) => `UGX ${value.toLocaleString('en-US', { minimumFractionDigits: 2 })}`
const timeGreeting = (date: Date) => { const hour = date.getHours(); return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening' }
type Insight = { type: string; title: string; detail: string }
type AuthUser = { username: string; email: string }

function AuthScreen({ onAuthenticated }: { onAuthenticated: (token: string, user: AuthUser, remember: boolean) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [previewDate] = useState(() => new Date())
  const [previewExpenses] = useState(initialExpenses.reduce((sum, expense) => sum + expense.amount, 0))
  const [previewInventoryValue] = useState(initialInventory.reduce((sum, item) => sum + item.value, 0))
  const [previewAlerts] = useState(initialInventory.filter((item) => item.status !== 'In stock').length)
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [identifier, setIdentifier] = useState('')
  const [remember, setRemember] = useState(true)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setError('')
    setLoading(true)
    try {
      const response = await fetch(`/api/auth/${mode}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(mode === 'login' ? { identifier, password } : { username, email, password }),
      })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || 'Authentication failed')
      onAuthenticated(result.token, result.user, remember)
    } catch (authError) {
      setError(authError instanceof Error ? authError.message : 'Authentication failed')
    } finally {
      setLoading(false)
    }
  }

  return <main className="auth-shell">
    <section className="auth-card">
      <div className="auth-brand"><span className="brand-mark"><CircleDollarSign size={21} /></span><span><strong>Ledgerly</strong><small>Expense & Inventory Management</small></span></div>
      <span className="auth-security"><ShieldCheck size={14} /> Secure · Reliable · Built for your business</span>
      <div className="auth-copy"><h1>{mode === 'login' ? <>Welcome back <span>👋</span></> : 'Create your account'}</h1><p>{mode === 'login' ? 'Sign in to access your expenses, inventory, and grow your business.' : 'Set up a secure account to manage your business.'}</p></div>
      <form onSubmit={submit} className="auth-form">
        {mode === 'login' ? <label>Email or username<input value={identifier} onChange={(event) => setIdentifier(event.target.value)} autoComplete="username" placeholder="you@example.com" required /></label> : <><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" placeholder="Choose a username" required /></label><label>Email address<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="you@example.com" required /></label></>}
        <label>Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder={mode === 'login' ? 'Enter your password' : 'At least 8 characters'} minLength={8} required /></label>
        {mode === 'login' && <div className="auth-options"><label className="remember-option"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> Remember me</label><button type="button" className="forgot-link" onClick={() => setError('Password reset is not configured yet. Contact your business administrator to regain access.')}>Forgot password?</button></div>}
        {error && <p className="auth-error">{error}</p>}
        <button className="button primary auth-submit" disabled={loading}><LogIn size={16} /> {loading ? 'Please wait...' : mode === 'login' ? 'Sign in securely' : 'Create account'}</button>
      </form>
      {mode === 'login' && <div className="auth-social-note"><span>or continue with</span><small>Social sign-in is not enabled for this workspace.</small></div>}
      <p className="auth-switch">{mode === 'login' ? 'New to Ledgerly?' : 'Already have an account?'} <button onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p>
    </section>
    <aside className="auth-aside auth-showcase">
      <div className="showcase-trust"><span /> Trusted by growing businesses</div>
      <div className="showcase-copy"><span className="showcase-kicker">Simple&nbsp; · &nbsp;Smart&nbsp; · &nbsp;Powerful</span><h2>Make every<br /><em>shilling</em> count.</h2><p>Track expenses, manage inventory, and get real-time insights — all in one place. Spend less time worrying and more time growing.</p></div>
      <div className="showcase-features"><div><i className="feature-green"><BarChart3 size={18} /></i><span><strong>Track expenses</strong><small>Know where your money goes</small></span></div><div><i className="feature-blue"><Boxes size={18} /></i><span><strong>Manage inventory</strong><small>Stay on top of your stock</small></span></div><div><i className="feature-violet"><Receipt size={18} /></i><span><strong>Insightful reports</strong><small>Make data-driven decisions</small></span></div><div><i className="feature-orange"><Users size={18} /></i><span><strong>Manage your business</strong><small>Keep daily operations organized</small></span></div></div>
      <div className="showcase-preview"><div className="preview-top"><span><b /> Ledgerly</span><span>{previewDate.toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}</span></div><div className="preview-metrics"><div><small>Expenses</small><strong>{money(previewExpenses)}</strong></div><div><small>Stock value</small><strong>{money(previewInventoryValue)}</strong></div><div><small>Alerts</small><strong>{previewAlerts}</strong></div></div><div className="preview-content"><div className="preview-donut" /><div className="preview-lines"><i /><i /><i /><i /></div></div><div className="preview-footer"><span><i /> Business overview</span><span>{initialInventory.length} sample products</span></div></div>
      <blockquote>“Better tracking.<br />Smarter decisions.”<small>— Ledgerly</small></blockquote>
      <div className="showcase-orbit orbit-one" /><div className="showcase-orbit orbit-two" />
    </aside>
  </main>
}

function App() {
  const [token, setToken] = useState(() => localStorage.getItem('ledgerly_token') || sessionStorage.getItem('ledgerly_token') || '')
  const [currentUser, setCurrentUser] = useState<AuthUser | null>(() => { const stored = localStorage.getItem('ledgerly_user') || sessionStorage.getItem('ledgerly_user'); return stored ? JSON.parse(stored) : null })
  const [now, setNow] = useState(() => new Date())
  const [activeNav, setActiveNav] = useState('Overview')
  const [expenses, setExpenses] = useState(initialExpenses)
  const [inventory, setInventory] = useState(initialInventory)
  const [search, setSearch] = useState('')
  const [showExpenseForm, setShowExpenseForm] = useState(false)
  const [showItemForm, setShowItemForm] = useState(false)
  const [toast, setToast] = useState('')
  const [insights, setInsights] = useState<{ summary: string; insights: Insight[]; provider?: string } | null>(null)
  const [analysisLoading, setAnalysisLoading] = useState(false)
  const filteredInventory = useMemo(() => inventory.filter((item) => `${item.name} ${item.sku} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [inventory, search])
  const filteredExpenses = useMemo(() => expenses.filter((expense) => `${expense.description} ${expense.category} ${expense.date}`.toLowerCase().includes(search.toLowerCase())), [expenses, search])
  const totalExpenses = useMemo(() => expenses.reduce((total, expense) => total + expense.amount, 0), [expenses])
  const inventoryValue = useMemo(() => inventory.reduce((total, item) => total + item.value, 0), [inventory])
  const stockAlerts = useMemo(() => inventory.filter((item) => item.status !== 'In stock').length, [inventory])
  const categoryTotals = useMemo(() => expenses.reduce<Record<string, number>>((totals, expense) => { totals[expense.category] = (totals[expense.category] || 0) + expense.amount; return totals }, {}), [expenses])
  const outOfStockCount = useMemo(() => inventory.filter((item) => item.stock === 0).length, [inventory])
  const lowStockCount = useMemo(() => inventory.filter((item) => item.stock > 0 && item.stock <= item.reorderAt).length, [inventory])
  const inventoryHealth = inventory.length ? Math.round((inventory.filter((item) => item.status === 'In stock').length / inventory.length) * 100) : 0
  const categoryBreakdown = useMemo(() => Object.entries(categoryTotals).sort(([, a], [, b]) => b - a).map(([name, amount]) => ({ name, amount, percent: totalExpenses ? Math.round((amount / totalExpenses) * 100) : 0 })), [categoryTotals, totalExpenses])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3000) }
  const authHeaders = { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }
  useEffect(() => { const clock = window.setInterval(() => setNow(new Date()), 30000); return () => window.clearInterval(clock) }, [])
  useEffect(() => { if (!token) return; fetch('/api/data', { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.ok ? response.json() : Promise.reject(new Error('Your session has expired'))).then((data) => { setExpenses(data.expenses.map((expense: Expense) => ({ ...expense, color: expense.color || 'peach' }))); setInventory(data.inventory) }).catch(() => { localStorage.removeItem('ledgerly_token'); localStorage.removeItem('ledgerly_user'); setToken(''); setCurrentUser(null) }) }, [token])
  const handleAuthenticated = (newToken: string, user: AuthUser, remember: boolean) => { localStorage.removeItem('ledgerly_token'); localStorage.removeItem('ledgerly_user'); sessionStorage.removeItem('ledgerly_token'); sessionStorage.removeItem('ledgerly_user'); const storage = remember ? localStorage : sessionStorage; storage.setItem('ledgerly_token', newToken); storage.setItem('ledgerly_user', JSON.stringify(user)); setToken(newToken); setCurrentUser(user) }
  const logout = () => { localStorage.removeItem('ledgerly_token'); localStorage.removeItem('ledgerly_user'); sessionStorage.removeItem('ledgerly_token'); sessionStorage.removeItem('ledgerly_user'); setToken(''); setCurrentUser(null); setInsights(null) }
  const runAnalysis = () => { setAnalysisLoading(true); fetch('/api/analysis', { method: 'POST', headers: authHeaders, body: JSON.stringify({ expenses, inventory }) }).then((response) => response.json()).then(setInsights).catch(() => notify('Unable to run analysis')).finally(() => setAnalysisLoading(false)) }
  const addExpense = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const expense = { description: String(data.get('description') || 'New expense'), category: String(data.get('category') || 'Operations'), amount: Number(data.get('amount')) || 0 }; setExpenses((current) => [{ id: Date.now(), ...expense, date: 'Just now', color: 'peach' }, ...current]); fetch('/api/expenses', { method: 'POST', headers: authHeaders, body: JSON.stringify(expense) }).catch(() => undefined); setShowExpenseForm(false); notify('Expense added to your ledger') }
  const addItem = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const item = { name: String(data.get('name') || 'New item'), sku: String(data.get('sku') || 'NEW-001'), category: String(data.get('category') || 'Other'), stock: Number(data.get('stock')) || 0, reorderAt: Number(data.get('reorderAt')) || 0, value: Number(data.get('value')) || 0 }; const status = item.stock === 0 ? 'Out of stock' : item.stock <= item.reorderAt ? 'Low stock' : 'In stock'; setInventory((current) => [...current, { id: Date.now(), ...item, status }]); fetch('/api/inventory', { method: 'POST', headers: authHeaders, body: JSON.stringify(item) }).catch(() => undefined); setShowItemForm(false); notify('Inventory item added') }
  if (!token) return <AuthScreen onAuthenticated={handleAuthenticated} />
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><CircleDollarSign size={20} /></span><span className="brand-copy"><strong>Ledgerly</strong><small>Expense Tracker & Inventory</small></span></div><div className="workspace-switcher"><span className="avatar">{currentUser?.username.slice(0, 2).toUpperCase() || 'BU'}</span><span><strong>{currentUser?.username || 'My business'}</strong><small>Business workspace</small></span><ChevronDown size={15} /></div><nav className="main-nav" aria-label="Main navigation"><p className="nav-label">Workspace</p>{navItems.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setActiveNav(label)}><Icon size={18} /><span>{label}</span>{label === 'Inventory' && stockAlerts > 0 && <span className="nav-badge">{stockAlerts}</span>}</button>)}<button className="nav-item" onClick={() => setActiveNav('Categories')}><Ticket size={18} /><span>Categories</span></button><button className="nav-item" onClick={() => notify('Supplier management is coming soon')}><ShoppingCart size={18} /><span>Suppliers</span></button><p className="nav-label nav-label-lower">Manage</p><button className="nav-item" onClick={() => notify('Settings are coming soon')}><Settings size={18} /><span>Settings</span></button></nav><section className="sidebar-health"><div className="health-label"><span><i /> Business health</span><span>{inventoryHealth}%</span></div><div className="health-ring" style={{ background: `conic-gradient(#11d6ae ${inventoryHealth}%, #25436a ${inventoryHealth}% 100%)` }}><span><strong>{inventoryHealth}%</strong><small>In stock</small></span></div><div className="health-caption"><ArrowUpRight size={14} /> {inventory.length - stockAlerts}/{inventory.length} products available</div><small className="health-quote">“Better tracking.<br />Smarter decisions.”</small></section><button className="nav-item logout-nav" onClick={logout}><LogIn size={18} /><span>Log out</span></button></aside>
    <main className="main-content"><header className="topbar"><div className="global-search"><Search size={17} /><input placeholder="Search expenses, products, or suppliers..." value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="header-note"><span className="note-mark">✦</span><span>Consistent tracking<br />leads to greater growth.</span></div><div className="top-actions"><button className="date-pill" title={now.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}><CalendarDays size={15} /> {now.toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</button><button className="icon-button" aria-label="Notifications" onClick={() => notify('You are all caught up')}><Bell size={18} /><i /></button><button className="account-profile" onClick={logout} title="Log out"><span className="top-avatar account-button">{currentUser?.username.slice(0, 2).toUpperCase() || 'BU'}</span><span className="profile-copy"><strong>{currentUser?.username || 'Business owner'}</strong><small>Business owner</small></span><ChevronDown size={14} /></button></div></header><div className="content-wrap">
      <section className="page-heading"><div><p className="eyebrow">{now.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })} <span className="current-time">· {now.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</span></p><h1>{timeGreeting(now)}, {currentUser?.username || 'there'} <span>👋</span></h1><p className="subheading">Here is what is happening with your business today.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => setShowExpenseForm(true)}><Plus size={17} /> Add expense</button><button className="button primary" onClick={() => setShowItemForm(true)}><PackagePlus size={17} /> Add inventory</button></div></section>
      <section className="metric-grid reference-metrics" aria-label="Business summary"><article className="metric-card"><div className="metric-top"><span>Total expenses</span><span className="metric-icon green"><Wallet size={17} /></span></div><strong>{money(totalExpenses)}</strong><div className="metric-trend up"><ArrowDownRight size={14} /> {expenses.length} <span>recorded entries</span></div></article><article className="metric-card"><div className="metric-top"><span>Total inventory value</span><span className="metric-icon blue"><Boxes size={17} /></span></div><strong>{money(inventoryValue)}</strong><div className="metric-trend up"><ArrowUpRight size={14} /> {inventory.length} <span>tracked products</span></div></article><article className="metric-card"><div className="metric-top"><span>Expense categories</span><span className="metric-icon violet"><Receipt size={17} /></span></div><strong>{Object.keys(categoryTotals).length}</strong><div className="metric-trend neutral"><span>Categories with recorded spending</span></div></article><article className="metric-card"><div className="metric-top"><span>Stock alerts</span><span className="metric-icon orange"><Boxes size={17} /></span></div><strong>{stockAlerts}</strong><div className="metric-trend down"><ArrowDownRight size={14} /> {outOfStockCount} out of stock <span>· {lowStockCount} low</span></div></article></section>
      <section className="reference-grid"><article className="panel expense-overview"><div className="panel-heading"><div><h2>Expense overview</h2><p>Recorded spending by category</p></div><span className="period-label"><CalendarDays size={14} /> This account</span></div>{categoryBreakdown.length ? <div className="expense-breakdown"><div className="donut-wrap"><div className="expense-donut" style={{ background: `conic-gradient(${categoryBreakdown.map((_, index) => `${['#1677ed', '#f59e0b', '#10b981', '#8b5cf6', '#ec4899', '#64748b'][index % 6]} ${categoryBreakdown.slice(0, index).reduce((sum, previous) => sum + previous.percent, 0)}% ${categoryBreakdown.slice(0, index + 1).reduce((sum, current) => sum + current.percent, 0)}%`).join(', ')})` }}><span><small>Total expenses</small><strong>{money(totalExpenses)}</strong></span></div></div><div className="category-legend">{categoryBreakdown.slice(0, 6).map((item, index) => <div className="legend-row" key={item.name}><i style={{ background: ['#1677ed', '#f59e0b', '#10b981', '#8b5cf6', '#ec4899', '#64748b'][index % 6] }} /><span>{item.name}</span><strong>{money(item.amount)}</strong><small>{item.percent}%</small></div>)}</div></div> : <div className="empty-chart"><Receipt size={25} /><strong>No expenses recorded yet</strong><span>Add an expense to see your category breakdown.</span></div>}</article><article className="panel stock-panel reference-stock"><div className="panel-heading"><div><h2>Inventory stock levels</h2><p>Stock that may need attention</p></div><button className="text-button" onClick={() => setActiveNav('Inventory')}>View all <ArrowUpRight size={14} /></button></div><div className="reference-stock-list">{inventory.slice(0, 6).map((item) => <div className="reference-stock-row" key={item.id}><span className="reference-product-icon"><Boxes size={17} /></span><span className="reference-product"><strong>{item.name}</strong><small>{item.stock} units · {item.sku}</small></span><span className={`table-status ${item.status === 'In stock' ? 'good' : item.status === 'Low stock' ? 'warning' : 'danger'}`}>{item.status}</span></div>)}</div></article><article className="panel quick-actions"><div className="panel-heading"><div><h2>Quick actions</h2><p>Common tasks</p></div></div><button className="quick-action expense-action" onClick={() => setShowExpenseForm(true)}><Plus size={18} /><span><strong>Add expense</strong><small>Record a new expense</small></span></button><button className="quick-action inventory-action" onClick={() => setShowItemForm(true)}><PackagePlus size={18} /><span><strong>Add product</strong><small>Update inventory stock</small></span></button><button className="quick-action reports-action" onClick={runAnalysis}><BarChart3 size={18} /><span><strong>View reports</strong><small>Analyze your business data</small></span></button></article></section>
      <section className="ai-panel panel"><div className="ai-heading"><div className="ai-title"><span className="ai-icon"><Sparkles size={17} /></span><div><h2>AI business analysis</h2><p>Get practical recommendations from your latest expenses and stock levels.</p></div></div><button className="button primary" onClick={runAnalysis} disabled={analysisLoading}><Sparkles size={15} /> {analysisLoading ? 'Analyzing...' : 'Analyze now'}</button></div>{insights ? <div className="insight-grid">{insights.insights.map((insight) => <div className={`insight-card ${insight.type}`} key={insight.title}><strong>{insight.title}</strong><p>{insight.detail}</p></div>)}</div> : <div className="ai-empty">Run an analysis to surface cash-flow patterns, spending concentration, and stock risks. <span>Powered by Ledgerly AI</span></div>}</section>
        <section className="panel category-panel"><div className="panel-heading"><div><h2>Expense planner</h2><p>See how your spending is distributed across business categories.</p></div><button className="text-button" onClick={() => setShowExpenseForm(true)}>Add expense <Plus size={14} /></button></div><div className="category-grid">{expenseCategories.map(({ name, icon: Icon, color }) => <button className={`category-card ${color}`} key={name} onClick={() => setShowExpenseForm(true)}><span className="category-art"><Icon size={19} /></span><span className="category-info"><strong>{name}</strong><small>{money(categoryTotals[name] || 0)}</small></span><ArrowUpRight size={14} /></button>)}</div></section>
      <section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-heading"><div><h2>Cash flow</h2><p>Income and expenses over time</p></div><select aria-label="Cash flow period"><option>Last 6 months</option><option>This year</option></select></div><div className="chart-legend"><span><i className="legend-income" /> Income</span><span><i className="legend-expense" /> Expenses</span></div><div className="chart"><div className="y-axis"><span>UGX 8k</span><span>UGX 6k</span><span>UGX 4k</span><span>UGX 2k</span><span>UGX 0</span></div><div className="chart-area"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 620 190" preserveAspectRatio="none" role="img" aria-label="Cash flow trend chart"><path className="income-line" d="M0 138 C40 130 55 144 92 111 S143 125 180 89 S235 117 270 68 S320 97 362 80 S410 93 450 49 S505 77 545 32 S584 52 620 19" /><path className="expense-line" d="M0 160 C43 151 55 155 92 132 S142 147 180 116 S235 140 270 119 S320 124 362 101 S410 119 450 91 S500 116 545 85 S585 96 620 75" /><path className="income-fill" d="M0 138 C40 130 55 144 92 111 S143 125 180 89 S235 117 270 68 S320 97 362 80 S410 93 450 49 S505 77 545 32 S584 52 620 19 V190 H0 Z" /></svg><div className="x-axis"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></div></article>
      <article className="panel stock-panel"><div className="panel-heading"><div><h2>Stock alerts</h2><p>Items that need your attention</p></div><button className="text-button" onClick={() => setActiveNav('Inventory')}>View all <ArrowUpRight size={15} /></button></div><div className="alert-list">{inventory.filter((item) => item.status !== 'In stock').map((item) => <div className="alert-row" key={item.id}><div className={`product-dot ${item.status === 'Out of stock' ? 'red' : 'orange'}`}><Boxes size={16} /></div><div className="alert-name"><strong>{item.name}</strong><span>{item.sku}</span></div><div className={`status ${item.status === 'Out of stock' ? 'out' : 'low'}`}>{item.status}</div><button className="more-button" aria-label={`More options for ${item.name}`}><MoreHorizontal size={17} /></button></div>)}</div><div className="stock-summary"><span><i className="dot red-dot" /> 1 out of stock</span><span><i className="dot orange-dot" /> 2 low stock</span></div></article></section>
      <section className="lower-grid"><article className="panel expense-panel"><div className="panel-heading"><div><h2>Recent expenses</h2><p>Keep an eye on where your money goes</p></div><button className="text-button" onClick={() => setActiveNav('Expenses')}>View all <ArrowUpRight size={15} /></button></div><div className="expense-list">{filteredExpenses.slice(0, 4).map((expense) => <div className="expense-row" key={expense.id}><div className={`expense-icon ${expense.color}`}><Receipt size={17} /></div><div className="expense-name"><strong>{expense.description}</strong><span>{expense.category} <b>•</b> {expense.date}</span></div><strong className="expense-amount">-{money(expense.amount)}</strong></div>)}</div></article><article className="panel inventory-panel"><div className="panel-heading"><div><h2>Inventory snapshot</h2><p>Your most valuable items</p></div><button className="text-button" onClick={() => setActiveNav('Inventory')}>Manage <ArrowUpRight size={15} /></button></div><div className="inventory-table"><div className="table-header"><span>Product</span><span>Stock</span><span>Value</span></div>{filteredInventory.slice(0, 3).map((item) => <div className="table-row" key={item.id}><div className="table-product"><span className="product-thumb"><Boxes size={16} /></span><span><strong>{item.name}</strong><small>{item.category}</small></span></div><span className={`stock-count ${item.status === 'Low stock' ? 'warning' : item.status === 'Out of stock' ? 'danger' : ''}`}>{item.stock} units</span><strong>{money(item.value)}</strong></div>)}</div><div className="table-search"><Search size={16} /><input placeholder="Search expenses and inventory..." value={search} onChange={(event) => setSearch(event.target.value)} /></div></article></section>
    </div></main>
    {showExpenseForm && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setShowExpenseForm(false)}><form className="modal" onSubmit={addExpense}><div className="modal-header"><div><h2>Add expense</h2><p>Record a new business expense.</p></div><button type="button" className="close-button" onClick={() => setShowExpenseForm(false)} aria-label="Close"><X size={18} /></button></div><label>Description<input name="description" placeholder="e.g. Delivery supplies" required /></label><div className="form-row"><label>Category<select name="category"><option>Fixed expenses</option><option>Shopping</option><option>Food</option><option>Medical</option><option>Transportation</option><option>Fitness</option><option>Entertainment</option><option>Family & education</option><option>Operations</option><option>Inventory</option><option>Marketing</option><option>Payroll</option></select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" placeholder="0.00" required /></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setShowExpenseForm(false)}>Cancel</button><button className="button primary">Save expense</button></div></form></div>}
    {showItemForm && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setShowItemForm(false)}><form className="modal" onSubmit={addItem}><div className="modal-header"><div><h2>Add inventory item</h2><p>Keep your catalog up to date.</p></div><button type="button" className="close-button" onClick={() => setShowItemForm(false)} aria-label="Close"><X size={18} /></button></div><label>Product name<input name="name" placeholder="e.g. Espresso beans" required /></label><div className="form-row"><label>SKU<input name="sku" placeholder="COF-024" required /></label><label>Category<input name="category" placeholder="Coffee" required /></label></div><div className="form-row"><label>Units in stock<input name="stock" type="number" min="0" placeholder="0" required /></label><label>Reorder point<input name="reorderAt" type="number" min="0" placeholder="10" required /></label></div><label>Inventory value<input name="value" type="number" min="0" step="0.01" placeholder="0.00" required /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setShowItemForm(false)}>Cancel</button><button className="button primary">Save item</button></div></form></div>}
    {toast && <div className="toast"><span>✓</span>{toast}</div>}
  </div>
}
export default App
